### ISSUE TITLE
"coef" metric

### ISSUE THREAD

**Issue by eltonjrv** [biobakery/MTX_model#3]
Dear MTX_model team,

Thanks for developing such a great tool for MTX DE analysis.
I've just run it, and it seems results are making sense to my biological questions.
I'd just want to double-check on whether I can consider the "coef" values similarly to the log fold-change ratios that we usually see in regular single-organism RNA-Seq DE results?
If so, which log scale is that (natural, 2, 10, ...) ?

Thanks a lot,
Best,
Elton

**Comment by zhangycbnu** [comment]
Hi Elton,

Sorry for late my reply. The “coef” from the model represents the p coefficient fitting a linear model. We typically treat it as one type of “effect size” that interprets the degree of the expression difference between case and control, which has a similar meaning for log-fold changes. “coef” and log(FC) are calculated in a different way, and they might have similar trend but are not exactly the same values. If you run MTXmodel with “--transform LOG”, then the “coef” is calculated at log2 scale.

Thanks!
Yancong
